# fly.toml app configuration file generated for client-health-journey-hi75ba on 2025-05-06T21:17:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'client-health-journey-hi75ba'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
